month: "August"

model_selection: 
  Food and non-alcoholic beverages: 'AutoArima_'
  Alcoholic beverages and tobacco: 'AutoArima_'
  Clothing and footwear: 'AutoArima_'
  Housing and utilities: 'AutoArima_'
  Household contents and services: 'AutoArima_'
  Health: 'AutoArima_'
  Transport: 'AutoArima_'
  Communication: 'AutoArima_'
  Recreation and culture: 'AutoArima_'
  Education: 'AutoArima_'
  Restaurants and hotels: 'AutoArima_'
  Miscellaneous goods and services: 'AutoArima_'